version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data:


networks:
  default:
    driver: bridge
